### ISSUE TITLE
Add support for workspace-template.yaml so the user does not have to clone the operator-pipeline repo

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/operator-certification-operator#66]
## Is your feature request related to a problem? Please describe.
Right now the operator only `applies` tasks and pipelines to the cluster, this means that a user still has to still clone the repo in order to pass configurations into the `tkn` command for pipeline to be triggered and executed properly

## Describe the solution you'd like.
Since the operator is already cloning the repo, would we be able to create the `volumeClaimTemplate` so the user didn't have to? And then the user does not have to clone the repo and also pass the `volumeClaimTemplate` argument to the `tkn` command.

## Describe alternatives you've considered.
As a workout we just document that the user still needs to clone the repo

## Additional context.
CMD that the user executes
```
tkn pipeline start operator-ci-pipeline \
  --param git_repo_url=$GIT_REPO_URL \
  --param git_branch=main \
  --param bundle_path=$BUNDLE_PATH \
  --param env=prod \
  --workspace name=pipeline,volumeClaimTemplateFile=templates/workspace-template.yml \
  --workspace name=kubeconfig,secret=kubeconfig \
  --showlog
```

This link on [volumeClaimTemplate](https://tekton.dev/docs/pipelines/workspaces/#volumeclaimtemplate) might be helpful.
  
We also might need to support other files that live in the `/templates/` folder in the `operator-pipeline` repo.

**Comment by dcurran90** [comment]
update:
it's possible to run the pipeline with a command like the following:
`tkn pipeline start operator-ci-pipeline \
  --param git_repo_url=$GIT_REPO_URL \
  --param git_branch=main \
  --param bundle_path=$BUNDLE_PATH \
  --param env=prod \
  --workspace name=pipeline,claimName=pipeline-workspace-pvc \
  --workspace name=kubeconfig,secret=kubeconfig \
  --showlog`

where claimName refers to some PVC that was previously created. Still testing to see if this PVC can be reused or needs to be a new PVC for each run

**Comment by dcurran90** [comment]
The git-clone task removes old directory if it already exists which is good news and by default this is true

https://github.com/redhat-openshift-ecosystem/operator-pipelines/blob/main/ansible/roles/operator-pipeline/templates/openshift/tasks/git-clone.yml#L72-L75

https://github.com/redhat-openshift-ecosystem/operator-pipelines/blob/main/ansible/roles/operator-pipeline/templates/openshift/tasks/git-clone.yml#L189-L191

This may be desirable if we don't want extra volumes lying around but may also cause issues with multiple concurrent pipeline runs like there would be in production. Looks like we may need to default to just adding some README documentation like the following from tekton:

```
$ cat <<EOF > workspace-template.yaml
spec:
	accessModes:
		- ReadWriteOnce
	resources:
		requests:
  			storage: 1Gi
EOF
```

https://github.com/tektoncd/cli/blob/198e5f303db06e45518494d0d16fa2dd7a61b4ce/docs/cmd/tkn_pipeline_start.md

So that users don't have to clone the extra repo but still end up using new volumes for each run. 
Checking to see if a configmap can be utilized instead but this may end up being more work than necessary and creating an overly complex command line statement for minimal benefit.

**Comment by acornett21** [comment]
@jomkz Do you think going the documentation route that is in PR #106 should fix this issue? Or should we look to implement code?

**Comment by acornett21** [comment]
We have documented what the user should do to achieve this, which is [here](https://github.com/redhat-openshift-ecosystem/operator-certification-operator#execute-the-pipeline-development-iterations), we can close this issue.
