### ISSUE TITLE
Add support for private container registries

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/operator-certification-operator#7]
The operator should support private container registries as documented in the Operator Certification CI Pipeline Instructions.

https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/ci-pipeline.md#required-step-will-be-optional-soon---if-using-a-private-container-registry

**Comment by acornett21** [comment]
Key to be used in CR should be `docker-registry` when creating the secrete, since this is the value the pipeline uses.

**Comment by dcurran90** [comment]
This appears to already work as long as the user creates the `registry-dockerconfig-secret` and runs the following command:
`tkn pipeline start operator-ci-pipeline \
  --param git_repo_url=$GIT_REPO_URL \
  --param git_branch=main \
  --param bundle_path=$BUNDLE_PATH \
  --param env=prod \
  --param pin_digests=true \
  --param git_username=$GIT_USERNAME \
  --param git_email=$GIT_EMAIL \
  --param registry=$REGISTRY \
  --param image_namespace=$IMAGE_NAMESPACE \
  --workspace name=pipeline,volumeClaimTemplateFile=templates/workspace-template.yml \
  --workspace name=kubeconfig,secret=kubeconfig \
  --workspace name=ssh-dir,secret=github-ssh-credentials \
  --workspace name=registry-credentials,secret=registry-dockerconfig-secret \
  --showlog`

we can check if the secret exists and log this in the operator but since we aren't creating secrets in the operator itself there isn't a lot for the operator to do

**Comment by jomkz** [comment]
That seems reasonable to me. So the work required for this would be to simply output a message in the log if the secret is present. Does anyone have any problem with that?

**Comment by dcurran90** [comment]
I'll open that PR right now so folks can see it.
